rating/api/urls.py
from api import views

from django.urls import include, path

from rest_framework import routers


app_name = 'api'

router = routers.SimpleRouter()
router.register('students', views.StudentViewSet)              # [+]
router.register('results', views.ResultViewSet)                # [+]
router.register('groups', views.GroupsViewSet)                 # [+]
router.register('cathedras', views.CathedraViewSet)            # [+]
router.register('faculties', views.FacultyViewSet)             # [+]
router.register('subjects', views.SubjectViewSet)              # [+]
router.register('groupsubjects', views.GroupSubjectViewSet)    # [+]

urlpatterns = [
    path('v1/', include(router.urls)),
    path('v1/activestudents/', views.StudentsList.as_view()),            # [+]
    path('v1/history/students/', views.StudentLogList.as_view()),        # [+]
    path('v1/archivedstudents/', views.StudentsArchivedList.as_view()),  # [+]
    path('v1/studentresults/', views.ResultsForStudentList.as_view()),   # [+]
    path('v1/studentsdebts/', views.students_debts),                     # [+]
    path('v1/studentsalldebts/', views.students_all_debts),              # [+]

    path('v1/activesubjects/', views.SubjectsList.as_view()),            # [+]
    # path('v1/history/subjects/', views.SubjectLogList.as_view()),        # [-]
    path('v1/archivedsubjects/', views.SubjectsArchivedList.as_view()),  # [+]
    path('v1/archivedresults/', views.ResultsArchivedList.as_view()),    # [+]
    path('v1/subjectresults/', views.ResultsForSubjectList.as_view()),   # [+]
    path('v1/activegroupsubjects/', views.GroupSubjectsList.as_view()),  # [+]
    path('v1/money/', views.StudentMoneyList.as_view()),                 # [+]
    # path('v1/rating/', views.student_rating),  # [-]

    path('v1/resetgroupsubjects/', views.reset_groupsubjects),  # [+]

    path('v1/transfer/students/', views.transfer_students),  # [+]
    path('v1/groupmarks/', views.group_marks),               # [+]

    path('v1/import/students/', views.import_students),              # [+]
    path('v1/import/results/', views.import_results),                # [+]
    path('v1/import/cathedras/', views.import_cathedras),            # [+]
    path('v1/import/subjects/', views.import_subjects),              # [+]
    path('v1/import/groupsubjects/', views.import_groupsubjects),    # [+]
]

rating/archive/urls.py
from archive import views

from django.urls import path


app_name = 'archive'

urlpatterns = [
    path('', views.ArchiveDataView.as_view(), name='archive'),
    path('help', views.HelpPageView.as_view(), name='help'),
]

rating/groups/urls.py
from django.urls import path

from groups import views


app_name = 'groups'

urlpatterns = [
    path('', views.GroupView.as_view(), name='groups'),
    path('cards/', views.GroupCardsView.as_view(), name='cards'),
    path('cards/<str:groupname>-<int:semester>/', views.GroupDetailListView.as_view(), name='detail'),
]

rating/rating/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.shortcuts import render


urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/groups/cards')),
    path('archive/', include('archive.urls', namespace='archive')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('students/', include('students.urls', namespace='students')),
    path('subjects/', include('subjects.urls', namespace='subjects')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls', namespace='api')),
]


def custom_404(request, exception=None):
    return render(request, '404.html', status=404)


handler404 = custom_404

rating/students/urls.py
from django.urls import path

from students import views


app_name = 'students'

urlpatterns = [
    # Students
    path('', views.StudentView.as_view(), name='students'),
    path('<int:pk>/', views.StudentDetailView.as_view(), name='detail'),

    # Graduates
    path('graduates/', views.GraduatesView.as_view(), name='graduates'),

    # Students debts
    path('debts/', views.StudentsDebtsView.as_view(), name='debts'),
    path('debts/all/', views.StudentsAllDebtsView.as_view(), name='all-debts'),
    path('debts/debts-to-excel/', views.download_excel_data, name='debts-to-excel'),

    # Students rating
    path('rating/', views.StudentRatingTableView.as_view(), name='rating'),
    path('json/rating/', views.StudentRatingApiView.as_view(), name='students_rating'),

    # Students money
    path('money/', views.StudentsMoneyListView.as_view(), name='money'),

    # Searching
    path('search/', views.search_results, name='search'),
]

rating/subjects/urls.py
from django.urls import path

from subjects import views


app_name = 'subjects'

urlpatterns = [
    path('', views.SubjectView.as_view(), name='subjects'),
    path('<int:pk>/', views.SubjectDetailView.as_view(), name='detail'),
    path('debts/', views.SubjectsDebtsListView.as_view(), name='debts'),
    path('faculties/', views.FacultyView.as_view(), name='faculties'),
    path('cathedras/', views.CathedraView.as_view(), name='cathedras'),
    path('groupsubjects/', views.GroupSubjectView.as_view(), name='groupsubjects'),
]

rating/templates/base.html
<!DOCTYPE html>

{% load static %}

{% load i18n %}

<html lang="ru">
    <head>
        <meta charset="utf-8">

        <!-- jQuery & DataTables -->
        <link href="{% static 'css/datatables.min_3.2.4.css' %}" rel="stylesheet">
        <script type="text/javascript" src="{% static 'js/datatables_3.2.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/dataTables.fixedColumns_4.1.0.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/dataTables.fixedHeader_3.2.3.min.js' %}"></script>
        
        <!-- fomantic ui -->
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.2/semantic.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.2/semantic.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.2/components/transition.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.2/components/transition.min.js"></script>

        <!-- Custom CSS -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">

        <!-- Hack font -->
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/hack-font@3/build/web/hack.css">

        <title>{% block title %}{% endblock %}</title>
    </head>

<body>

<!-- Header -->
<header>
    <div class="ui container">
        <div id="header" class="ui pointing inverted small top fixed borderless menu" style="font-family: Hack">

            <!-- Left side header -->
            <a class="item" href="{% url 'groups:cards' %}"><i class="home large icon"></i></a>
            <a id="toggle" class="item"><h4 style="font-family: Hack">Рейтинг успеваемости ФИЭиГХ</h4></a>

            <!-- Right side header -->
            <div class="right menu">
                <!-- Job time info -->
                <div id="job-time" class="item"></div>
                <!-- FAQ -->
                <a class="item" href="{% url 'archive:help' %}">Справка</a>
                <!-- Search -->
                <div class="item">
                    <form action="{% url 'students:search' %}" method="GET">
                        {% csrf_token %}
                        <div class="ui inverted transparent icon small input">
                            <input name="search" type="search" placeholder="Поиск..." style="font-family: Hack">
                        </div>
                    </form>
                </div>
                <!-- Logged username -->
                {% if user.is_authenticated %}
                    <a class="item" href="{% url 'logout' %}">{% if user.last_name %}{{ user.last_name }}{% else %}{{ user.username }}{% endif %}</a>
                {% else %}
                    <a class="item">Вход</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

<!-- Menu -->
<nav class="nav">
    <ul>
        <li><a class="header" href="{% url 'groups:cards' %}"><i class="users icon"></i> Группы</a>
        <li><a class="header" href="{% url 'dashboard:dashboard' %}"><i class="calculator icon"></i> Статистика</a>
        <li><a class="header" href="{% url 'students:money' %}"><i class="hand holding usd icon"></i> Стипендия</a>
        <li><a class="header" href="{% url 'students:rating' %}"><i class="star yellow icon"></i> Средний балл</a>

        <div class="ui horizontal red divider">

        <li><div class="header"><i class="exclamation circle red icon"></i> Задолженности</div>
            <li><a class="item" href="{% url 'students:debts' %}"><i class="chevron right icon"></i>Текущие по студентам</a>
            <li><a class="item" href="{% url 'students:all-debts' %}"><i class="chevron right icon"></i>Все по студентам</a>
            <li><a class="item" href="{% url 'subjects:debts' %}"><i class="chevron right icon"></i>Текущие по дисциплинам</a>

        <div class="ui horizontal red divider">

            <li><div class="header"><i class="list ul green icon"></i> Списки</div>
            <li><a class="item" href="{% url 'students:students' %}"><i class="plus green icon"></i>Студенты</a>
            <li><a class="item" href="{% url 'subjects:subjects' %}"><i class="plus green icon"></i>Дисциплины</a>
            <li><a class="item" href="{% url 'subjects:groupsubjects' %}"><i class="plus green icon"></i>Назначения дисциплин</a>
            <li><a class="item" href="{% url 'groups:groups' %}"><i class="plus green icon"></i>Группы</a>
            <li><a class="item" href="{% url 'subjects:cathedras' %}"><i class="plus green icon"></i>Кафедры</a>
            <li><a class="item" href="{% url 'subjects:faculties' %}"><i class="plus green icon"></i>Факультеты</a>

        <div class="ui horizontal red divider">
        
        <li><a class="header" href="{% url 'archive:archive' %}"><i class="archive brown icon"></i> Архив</a>
        <li><a class="header" href="{% url 'students:graduates' %}"><i class="graduation blue cap icon"></i> Выпускники</a>
    </ul>
</nav>

<!-- Content -->
<div id="content" style="padding-bottom: 35px">
    {% if messages %}
        <div class="ui black tiny nag" style="display: block;">
            {% for message in messages %}
                {% if message.tags == 'info' %}
                    {% if forloop.counter == 1 %}
                        <div class="title">
                            <p>{{ message|safe }}</p>
                        </div>
                    {% else %}
                        <p align="left">{{ message|safe }}</p>
                    {% endif %}
                {% else %}
                    {% if forloop.counter == 1 %}
                        <div class="title">
                            <p>{{ message|safe }}</p>
                        </div>
                    {% else %}
                        <p align="left">{{ message|safe }}</p>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}

    {% block content %}{% endblock %}
</div>

<!-- Footer -->
<footer>
    <!-- Footer -->
    <div class="ui container">
        <div id="footer" class="ui footer mini segment" style="font-family: Hack">
            <div class="ui grid">
                <!-- Version -->
                <div id="text" class="eight wide column left aligned"><i class="react icon"></i>Version 1.1</div>
                <!-- Author -->
                <div id="text" class="eight wide column right aligned">
                    Iurii Polnikov <script>document.write(new Date().getFullYear())</script>|All Rights Reserved
                    <i class="paw icon"></i>
                </div>
            </div>
        </div>
    </div>
</footer>

</body>

<!-- Custom Scripts -->
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
<script type="text/javascript">
    $('.ui.dropdown').dropdown();
    $('.ui.rating').rating();
    $('.ui.nag').nag({displayTime: 10_000});
    $('div.ui.calendar')
        .calendar({
            type: 'date',
            blur: true,
            formatter: {
                date: 'DD.MM.YYYY'
            },
            text: {
                days: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
                months: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
                monthsShort: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
            },
            firstDayOfWeek: 1,
    });

    // функция закрытия меню
    function closeMenu() {
        let menu = document.querySelector("nav");
        menu.style.left = "-320px";
    };

    // закрытие меню, если курсор ушел с меню
    $(".nav").hover(function(){}, closeMenu);

    $('#toggle').click(
        function(){
            $('.nav').animate({
                left: '0px'
            }, 100);
        }
    );

    jobTimeInfo();
    setInterval("jobTimeInfo()", 60000);
</script>

</html>

rating/templates/empty_records.html
<div class="ui one column centered grid">
   <div class="one column"></div>
   <div class="ui center aligned container">
      <p>Данных нет...</p>
   </div>
   <div class="one column"></div>
</div>

rating/templates/search_results.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Результаты поиска{% endblock %}

{% block content %}

<div id="search" class="ui container center aligned">
    <div class="ui equal width grid">

        <div class="row">
            <div class="column">
                <form action="{% url 'students:search' %}" method="GET">
                    {% csrf_token %}
                    <div class="ui icon input" style="width: 500px">
                        <input name="search" type="search" placeholder="Поиск..." style="font-family: Hack">
                        <i class="search link icon"></i>
                    </div>
                </form>
            </div>
        </div>

        <div class="row">
            <h3 style="font-family: Hack">Результаты поиска по запросу: {% if  search %}<div class="ui grey large label">{{ search }}</div>{% endif %}</h3>
        </div>

        {% if not search %}
            <div class="row">
                <div class="column">
                    <div class="ui negative message"><div class="header" style="font-family: Hack">Пустой поиск</div></div>
                </div>
            </div>
        {% elif students or subjects or groupsubjects %}

            <div class="row">
                <div id="search-column" class="column">

                    <div class="ui segment left aligned">

                        <!-- Students -->
                        {% if students %}
                            {% for student in students %}
                                <div class="ui middle aligned selection list">
                                    <div class="item">
                                        <div class="content">
                                            <div class="header" style="font-family: Hack">
                                                <i class="user graduate icon"></i> <a href="{{ student.get_absolute_url }}">{{ student.fullname }}</a> | {{ student.comment }}
                                                <div class="ui basic circular label">
                                                    {{ student.group }}-{{ student.course }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}

                        <!-- Subjects -->
                        {% if subjects %}
                            {% for subject in subjects %}
                                <div class="ui middle aligned selection list">
                                    <div class="item">
                                        <div class="content">
                                            <div class="header" style="font-family: Hack">
                                                <i class="book icon"></i> <a href="{{ subject.get_absolute_url }}">{{ subject }}</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}

                        <!-- GroupSubjects -->
                        {% if groupsubjects %}
                            {% for gs in groupsubjects %}
                                <div class="ui middle aligned selection list">
                                    <div class="item">
                                        <div class="content">
                                            <div class="header" style="font-family: Hack">
                                                <i class="thumbtack icon"></i> {{ gs }} | {{ gs.comment }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}

                    </div>
                </div>
            </div>

        {% else %}
            <div class="row">
                <div class="column">
                    <div class="ui negative message"><div class="header" style="font-family: Hack">Ничего не найдено...</div></div>
                </div>
            </div>
        {% endif %}
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var column = document.getElementById('search-column');
        column.style.paddingRight = '0px';
        column.style.paddingLeft = '0px';
    })
</script>

{% endblock %}