rating/api/urls.py
from api import views

from django.urls import include, path

from rest_framework import routers


app_name = 'api'

router = routers.SimpleRouter()
router.register('students', views.StudentViewSet)              # [+]
router.register('results', views.ResultViewSet)                # [+]
router.register('groups', views.GroupsViewSet)                 # [+]
router.register('cathedras', views.CathedraViewSet)            # [+]
router.register('faculties', views.FacultyViewSet)             # [+]
router.register('subjects', views.SubjectViewSet)              # [+]
router.register('groupsubjects', views.GroupSubjectViewSet)    # [+]

urlpatterns = [
    path('v1/', include(router.urls)),
    path('v1/activestudents/', views.StudentsList.as_view()),            # [+]
    path('v1/history/students/', views.StudentLogList.as_view()),        # [+]
    path('v1/archivedstudents/', views.StudentsArchivedList.as_view()),  # [+]
    path('v1/studentresults/', views.ResultsForStudentList.as_view()),   # [+]
    path('v1/studentsdebts/', views.students_debts),                     # [+]
    path('v1/studentsalldebts/', views.students_all_debts),              # [+]

    path('v1/activesubjects/', views.SubjectsList.as_view()),            # [+]
    # path('v1/history/subjects/', views.SubjectLogList.as_view()),        # [-]
    path('v1/archivedsubjects/', views.SubjectsArchivedList.as_view()),  # [+]
    path('v1/archivedresults/', views.ResultsArchivedList.as_view()),    # [+]
    path('v1/subjectresults/', views.ResultsForSubjectList.as_view()),   # [+]
    path('v1/activegroupsubjects/', views.GroupSubjectsList.as_view()),  # [+]
    path('v1/money/', views.StudentMoneyList.as_view()),                 # [+]
    # path('v1/rating/', views.student_rating),  # [-]

    path('v1/resetgroupsubjects/', views.reset_groupsubjects),  # [+]

    path('v1/transfer/students/', views.transfer_students),  # [+]
    path('v1/groupmarks/', views.group_marks),               # [+]

    path('v1/import/students/', views.import_students),              # [+]
    path('v1/import/results/', views.import_results),                # [+]
    path('v1/import/cathedras/', views.import_cathedras),            # [+]
    path('v1/import/subjects/', views.import_subjects),              # [+]
    path('v1/import/groupsubjects/', views.import_groupsubjects),    # [+]
]

rating/rating/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.shortcuts import render


urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/groups/cards')),
    path('archive/', include('archive.urls', namespace='archive')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('students/', include('students.urls', namespace='students')),
    path('subjects/', include('subjects.urls', namespace='subjects')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls', namespace='api')),
]


def custom_404(request, exception=None):
    return render(request, '404.html', status=404)


handler404 = custom_404

rating/students/urls.py
from django.urls import path

from students import views


app_name = 'students'

urlpatterns = [
    # Students
    path('', views.StudentView.as_view(), name='students'),
    path('<int:pk>/', views.StudentDetailView.as_view(), name='detail'),

    # Graduates
    path('graduates/', views.GraduatesView.as_view(), name='graduates'),

    # Students debts
    path('debts/', views.StudentsDebtsView.as_view(), name='debts'),
    path('debts/all/', views.StudentsAllDebtsView.as_view(), name='all-debts'),
    path('debts/debts-to-excel/', views.download_excel_data, name='debts-to-excel'),

    # Students rating
    path('rating/', views.StudentRatingTableView.as_view(), name='rating'),
    path('json/rating/', views.StudentRatingApiView.as_view(), name='students_rating'),

    # Students money
    path('money/', views.StudentsMoneyListView.as_view(), name='money'),

    # Searching
    path('search/', views.search_results, name='search'),
]

rating/students/views.py
import concurrent.futures
import logging

from collections import Counter
from openpyxl import Workbook
from openpyxl.styles import Font

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, F
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.generic import (DetailView, ListView, View, TemplateView,)

from groups.models import Group
from students.forms import ResultForm, StudentForm
from students.models import Result, Semester, Student, StudentLog
from subjects.models import Cathedra, GroupSubject, Subject
from rating.functions import calculate_rating


logger = logging.getLogger(__name__)


class StudentView(LoginRequiredMixin, TemplateView):
    template_name = 'students/students.html'


    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['students'] = Student.active_objects.all().count()
        context['form'] = StudentForm()
        return context


class StudentDetailView(LoginRequiredMixin, DetailView):
    model = Student

    def get(self, request, pk, **kwargs):
        student = get_object_or_404(Student.objects.select_related('group', 'semester', 'basis'), student_id__exact=pk)

        try:
            history = StudentLog.objects.select_related('user').filter(
                record_id=student.student_id).order_by('-timestamp').values()
        except Exception as ex:
            logger.info(f'[-] История изменений по студенту {student} отсутствует', extra={'Exception': ex})
            history = 'Error'

        # all student marks
        marks = Result.objects.select_related().filter(
            students=student.student_id).filter(
            ~Q(groupsubject__subjects__form_control__exact='Зачет'))
        # all group results exclude non-nu,eric marks
        atts = GroupSubject.objects.select_related('subjects'
            ).filter(groups=student.group
            ).filter(~Q(subjects__form_control__exact='Зачет'))

        # calculation of the average ranking for semesters and the total
        rating_by_semester_bac = {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
        }
        rating_by_semester_mag = {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
        }
        debts_by_semester_bac = {
            1: [],
            2: [],
            3: [],
            4: [],
            5: [],
            6: [],
            7: [],
            8: [],
        }
        debts_by_semester_mag = {
            1: [],
            2: [],
            3: [],
            4: [],
        }

        all_num_marks = []
        all_marks = []
        if student.level == Student.Level.BAC:
            semesters = range(1, 9)
            rating_by_semester = rating_by_semester_bac
            debts_by_semester = debts_by_semester_bac
        elif student.level == Student.Level.MAG:
            semesters = range(1, 5)
            rating_by_semester = rating_by_semester_mag
            debts_by_semester = debts_by_semester_mag

        for i in semesters:
            # all marks per semester
            sem_marks_all = marks.select_related('subjects').filter(
                groupsubject__subjects__semester__semester=i
            ).values('mark')
            # take only the last mark and exclude <ня> и <2>
            sem_marks = list(filter(lambda x: x not in ['ня', '2'], [i['mark'][-1] for i in sem_marks_all]))
            all_marks += sem_marks
            # quantity of groupsubjects with marks per semester
            num_atts = atts.filter(subjects__semester=i).count()
            all_num_marks.append(num_atts)
            # quantity of each mark <3 | 4 | 5>
            count_marks = dict(Counter(sem_marks))

            # calculate average ranking per semester
            if num_atts:
                sem_rating = round(sum([int(k)*v for k, v in count_marks.items()]) / num_atts, 2)
            else:
                sem_rating = 0

            rating_by_semester[i] = sem_rating

        # calculate total ranking
        if sum(all_num_marks):
            rating = round(sum(list(map(int, (all_marks)))) / sum(all_num_marks), 2)
        else:
            rating = 0

        negative = ['ня', 'нз', '2']
        marks = Result.objects.select_related().filter(
            students=student.student_id,
            is_archived=False,
        ).annotate(semester=F('groupsubject__subjects__semester__semester')
        ).values(
            'semester',
            'mark',
        )
        debts_by_level_per_semester = {
            1: [],
            2: [],
            3: [],
        }
        debts_data = {}

        for record in marks:
            semester = record['semester']
            mark = record['mark']
            debts_by_semester[semester].append(mark)

        for k, v in debts_by_semester.items():
            all_marks = v
            marks_att1 = [i[0] for i in all_marks]
            marks_att2 = [i[1] for i in list(filter(lambda x: len(x) in [2, 3], all_marks))]
            marks_att3 = [i[2] for i in list(filter(lambda x: len(x) == 3, all_marks))]
            count_marks_att1 = dict(Counter(marks_att1))
            count_marks_att2 = dict(Counter(marks_att2))
            count_marks_att3 = dict(Counter(marks_att3))
            debts_1 = sum(list(map(lambda x: count_marks_att1.get(x, 0), negative)))
            debts_2 = sum(list(map(lambda x: count_marks_att2.get(x, 0), negative)))
            debts_3 = sum(list(map(lambda x: count_marks_att3.get(x, 0), negative)))
            debts_data[k] = [debts_1, debts_2, debts_3]

        for s in range(1, 4):
            debts_by_level_per_semester[s] = [i[s-1] if i else 0 for i in debts_data.values()]
            debts_by_level_per_semester[s].append(sum(debts_by_level_per_semester[s]))

        form = StudentForm()
        context = {
            'student': student,
            'history': history,
            'rating': rating,
            'rating_by_semester': rating_by_semester,
            'form': form,
            'result_form': ResultForm(),
            'debts_by_level_per_semester': debts_by_level_per_semester,
        }
        return render(request, 'students/student_detail.html', context=context)


class StudentRatingTableView(LoginRequiredMixin, ListView):
    """Head of table of the students average ranking. Semesters"""
    def get(self, request):
        semesters = Semester.objects.all()
        groups = Group.objects.filter(is_archived=False)
        return render(request, 'students/students_rating.html', context={'semesters': semesters,
                                                                         'groups': groups})


class StudentRatingApiView(LoginRequiredMixin, View):
    """Calculating of the students average ranking."""
    def get(self, request):
        logger.info(f'Расчет среднего балла...')
        serialized_data = []
        sem_start = request.GET.get('semStart', '')
        sem_stop = request.GET.get('semStop', '')
        groups = request.GET.getlist('groups[]', False)

        if sem_start:
            start = sem_start
        else:
            start = 1

        if groups:
            students = Student.active_objects.select_related('group', 'semester', 'basis').filter(
                group__name__in=groups, semester__semester__gte=start)
        else:
            students = Student.active_objects.select_related(
                'group', 'semester', 'basis').filter(
                semester__semester__gte=start)

        flag_1 = not sem_start and not sem_stop
        flag_2 = sem_start and not sem_stop
        flag_3 = not sem_start and sem_stop
        flag_4 = sem_start and sem_stop == '-'

        if flag_1 or flag_2 or flag_3 or flag_4:
            logger.info(f'|---> Расчет среднего балла за семестр {start} для студентов группы {groups}')

            with concurrent.futures.ThreadPoolExecutor() as executor:
                # the students average ranking for specified semester. default - for 1t
                future_to_student = {
                    executor.submit(calculate_rating, student, start): student
                    for student in students
                }
                for future in concurrent.futures.as_completed(future_to_student):
                    student = future_to_student[future]
                    try:
                        rating = future.result()
                    except Exception as exc:
                        logger.error(f'calculation of student {student.student_id} rating failed: {exc}')
                    else:
                        serialized_data.append({
                            'studentId': student.student_id,
                            'fullname': student.fullname,
                            'group': student.group.name,
                            'currentSemester': student.semester.semester,
                            'basis': student.basis.name,
                            'level': student.level,
                            'rating': rating,
                            'isIll': student.is_ill,
                            'tag': student.tag,
                        })
        else:
            # the students average ranking for specified period
            start, stop = sem_start, sem_stop
            logger.info(f'Расчет среднего балла за период с {start} по {stop} семестр для студентов группы {groups}')

            with concurrent.futures.ThreadPoolExecutor() as executor:
                future_to_student = {
                    executor.submit(calculate_rating, student, start, stop): student
                    for student in students
                }
                for future in concurrent.futures.as_completed(future_to_student):

rating/students/templates/students/graduates.html
{% extends "base.html" %}

{% load static %}

{% load customfilters %}

{% block title %}Выпускники{% endblock %}

{% block content %}

<div id="segments" class="ui basic segments">

{% if graduates %}
	<!-- Title -->
	<div class="ui basic segment">
        <div class="ui stackable two column grid">
            <div class="column"><h2 style="font-family: Hack">Выпускники</h2></div>
        </div>
    </div>

	<!-- Table -->
	<div id="datatable-segment" class="ui basic segment">
        <table id="graduates-table" class="ui selectable celled compact fixed single line table">
            <thead>
                <tr class="center aligned">
                    <th id="numbers"><i class="hashtag small icon"></i></th>
                    <th>ФИО
                        <div id="count-label" class="ui left pointing grey tiny label">{{ graduates.count }}</div>
                    </th>
                    <th>Группа</th>
                    <th>Семестр</th>
                    <th>Год выпуска</th>
                    <th>Примечание</th>
                </tr>
            </thead>
            <tbody>
                {% for student in graduates %}
                    <tr>
                        <td class="center aligned collapsing" style="width: 50px">{{ forloop.counter }}</td>
                        <td class="collapsing">
                            <a href="{{ student.get_absolute_url }}">{{ student.fullname }}</a>
                            {% if student.tag %}
                                <div id="tag-label" class="ui small pink label">{{ student.tag }}</div>
                            {% endif %}
                        </td>
                        <td class="center aligned">{{ student.group }}</td>
                        <td class="center aligned">{{ student.semester.semester }}</td>

                        <td class="center aligned">{{ student.graduate_year|date:"Y" }}</td>
                        <td>{{ student.comment|truncatechars:25 }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
{% else %}
    {% include 'empty_records.html' %}
{% endif %}

<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        const dataTableOptions = {
			language: {
				lengthMenu: '_MENU_ записей на страницу',
				zeroRecords: 'Записей нет...',
				info: 'Всего записей: _MAX_',
				infoEmpty: '',
				infoFiltered: 'Найдено: _TOTAL_',
				search: '',
				searchPlaceholder: 'поиск',
				paginate: {
					first:    '«',
					previous: '‹',
					next:     '›',
					last:     '»'
				}
			},
			lengthMenu: [
				[20, 50, -1],
				[20, 50, 'Все']
			],
			pageLength: 20,
            searching: true,
			autoWidth: false,
			columnDefs: [
				{ width: "3%", targets: 0 },
				{ width: "37%", targets: 1 },
				{ width: "10%", targets: [2, 3, 4] },
				{ width: "30%", targets: 5 },
				{ searchable: false, targets: 0 },
			],
		};
		var table = $('#graduates-table').DataTable(dataTableOptions);
		changeDatatableInputFont();
    })
</script>

{% endblock %}

rating/students/templates/students/students_all_debts.html
<!DOCTYPE html>

{% extends "base.html" %}

{% load static %}

{% block title %}Все задолженности по студентам{% endblock %}

{% block content %}

<div id="segments" class="ui basic segments">

    <!-- Title & button -->
    <div id="buttons-segment" class="ui basic segment">
        <h2 style="font-family: Hack">Все задолженности по студентам в текущем семестре</h2>
    </div>

        <!-- Table -->
    <div id="datatable-segment" class="ui basic segment">
        <table id="students-debts" class="ui selectable celled compact small table">
            <!-- data from script -->
        </table>
    </div>
</div>

<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
<script type="text/javascript" src="{% static 'js/script_students_all_debts.js' %}"></script>
<script>
    $('.ui.radio.checkbox').checkbox();
    $(document).ready(function() {
        if ($.fn.DataTable.isDataTable('#students-debts')) {
            $('#students-debts').DataTable().destroy();
        };
        const dataTableOptions = {
			columns: [
                { title: '<i class="hashtag small icon"></i>' },
                { title: 'Группа' },
                { title: 'Семестр' },
                { title: 'Студент' },
                { title: 'Основа обучения' },
                { title: 'Сессия' },
                { title: 'Пересдача' },
                { title: 'Комиссия' },
            ],
			language: {
				lengthMenu: '_MENU_ записей на страницу',
				zeroRecords: 'Записей нет...',
				info: 'Всего записей: _MAX_',
				infoEmpty: '',
				infoFiltered: 'Найдено: _TOTAL_',
				search: '',
				searchPlaceholder: 'поиск',
				paginate: {
					first:    '«',
					previous: '‹',
					next:     '›',
					last:     '»'
				}
			},
			lengthMenu: [
				[20, 50, -1],
				[20, 50, 'Все']
			],
			pageLength: 20,
            searching: true,
			autoWidth: false,
			columnDefs: [
				{ width: "3%", targets: 0 },
				{ width: "7%", targets: [1, 2] },
				{ width: "43%", targets: 3 },
				{ width: "10%", targets: [4, 5, 6, 7] },
				{ searchable: false, targets: 0 },
                { className: 'center aligned', targets: [0, 1, 2, 4, 5, 6, 7] },
				{
					targets: 4,
					createdCell: function(td, cellData, rowData, row, col) {
                        switch(cellData) {
                            case 'Контракт':
                                $(td).addClass('negative');
                                break
                            case 'ИГ':
                                $(td).addClass('blue');
                                break
                        };
					}
				},
			],
			headerCallback: function(thead, cellData, start, end, display) {
                $(thead).find('th').addClass('center aligned');
            },
		};
		var table = $('#students-debts').DataTable(dataTableOptions);

        let firstRow = $('#students-debts thead tr')[0];
        let secondRow = firstRow.cloneNode(true);
        firstRow.after(secondRow);

        let filterColumns = $('#students-debts thead tr')[1].children;
        for (let i = 0; i < filterColumns.length; i++) {
            let inputWidth = filterColumns[i].offsetWidth - 60;
            if(i != 0) {
                filterColumns[i].innerHTML = `
                                                <div class="ui input">
                                                    <input name="filter" type="text" style="width: ${inputWidth}px" data-index=${i}>
                                                </div>
                                            `;
            } else {filterColumns[i].innerHTML = ""};
        };

        // Filter event handler
        $(table.table().container()).on('keyup', 'thead input', function() {table
            .column($(this).data('index'))
            .search(this.value)
            .draw();
        });

        // Clean filters inputs by double-clicking above the head
        $(document).on("dblclick",  ".ui.stackable.grid", function() {
            let inputs = document.getElementsByName("filter");
            inputs.forEach(e => {
                e.value = "";
            });
            table.search('');
            table.columns().search('').draw();
        });
		changeDatatableInputFont();
		removeSortingLabel('students-debts');
    });
</script>

{% endblock %}

rating/students/templates/students/students_debts.html
<!DOCTYPE html>

{% extends "base.html" %}

{% load static %}

{% block title %}Задолженности по студентам{% endblock %}

{% block content %}

<div id="segments" class="ui basic segments">

   <!-- Title & button -->
   <div id="buttons-segment" class="ui basic segment">
      <form id="form" action="{% url 'students:debts-to-excel' %}" method="GET">
         {% csrf_token %}
         <div class="ui stackable two column grid">
            <div class="eight wide column"><h2 style="font-family: Hack">Задолженности по студентам</h2></div>
            <div class="eight wide column right aligned">
               <button id="export-button" type="submit" class="ui positive small circular button" style="font-family: Hack"><i class="cloud download alternate icon"></i> Экспорт</button>
            </div>
            <div class="sixteen wide column right aligned">
               <div class="ui small form">
                  <div class="inline fields">
                     <div class="field">
                        <div class="ui radio checkbox checked">
                           <input type="radio" value="att1" name="att" id="att1" checked="" tabindex="0" class="hidden">
                           <label>Сессия</label>
                        </div>
                     </div>
                     <div class="field">
                        <div class="ui radio checkbox">
                           <input type="radio" value="att2" name="att" id="att2" tabindex="0" class="hidden">
                           <label>Пересдача</label>
                        </div>
                     </div>
                     <div class="field">
                        <div class="ui radio checkbox">
                           <input type="radio" value="att3" name="att" id="att3" tabindex="0" class="hidden">
                           <label>Комиссия</label>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </form>
   </div>

	<!-- Table -->
   <div id="datatable-segment" class="ui basic segment">
        <table id="students-debts" class="ui selectable celled compact small table">
			<!-- data from script -->
        </table>
    </div>
</div>

<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
<script type="text/javascript" src="{% static 'js/script_students_debts.js' %}"></script>
<script>
    $('.ui.radio.checkbox').checkbox();
    $(document).ready(function() {
        if ($.fn.DataTable.isDataTable('#students-debts')) {
            $('#students-debts').DataTable().destroy();
        };
        const dataTableOptions = {
			columns: [
                { title: '<i class="hashtag small icon"></i>' },
                { title: 'Группа' },
                { title: 'Семестр' },
                { title: 'Студент' },
                { title: 'Основа обучения' },
                { title: 'Сессия' },
                { title: 'Пересдача' },
                { title: 'Комиссия' },
            ],
			language: {
				lengthMenu: '_MENU_ записей на страницу',
				zeroRecords: 'Записей нет...',
				info: 'Всего записей: _MAX_',
				infoEmpty: '',
				infoFiltered: 'Найдено: _TOTAL_',
				search: '',
				searchPlaceholder: 'поиск',
				paginate: {
					first:    '«',
					previous: '‹',
					next:     '›',
					last:     '»'
				}
			},
			lengthMenu: [
				[20, 50, -1],
				[20, 50, 'Все']
			],
			pageLength: 20,
            searching: true,
			autoWidth: false,
			columnDefs: [
				{ width: "3%", targets: 0 },
				{ width: "7%", targets: [1, 2] },
				{ width: "43%", targets: 3 },
				{ width: "10%", targets: [4, 5, 6, 7] },
				{ searchable: false, targets: 0 },
                { className: 'center aligned', targets: [0, 1, 2, 4, 5, 6, 7] },
				{
					targets: 4,
					createdCell: function(td, cellData, rowData, row, col) {
                        switch(cellData) {
                            case 'Контракт':
                                $(td).addClass('negative');
                                break
                            case 'ИГ':
                                $(td).addClass('blue');
                                break
                        };
					}
				},
			],
			headerCallback: function(thead, cellData, start, end, display) {
                $(thead).find('th').addClass('center aligned');
            },
		};
		var table = $('#students-debts').DataTable(dataTableOptions);

        let firstRow = $('#students-debts thead tr')[0];
        let secondRow = firstRow.cloneNode(true);
        firstRow.after(secondRow);

        let filterColumns = $('#students-debts thead tr')[1].children;
        for (let i = 0; i < filterColumns.length; i++) {
            let inputWidth = filterColumns[i].offsetWidth - 60;
            if(i != 0) {
                filterColumns[i].innerHTML = `
                                                <div class="ui input">
                                                    <input name="filter" type="text" style="width: ${inputWidth}px" data-index=${i}>
                                                </div>
                                            `;
            } else {filterColumns[i].innerHTML = ""};
        };

        // Filter event handler
        $(table.table().container()).on('keyup', 'thead input', function() {table
            .column($(this).data('index'))
            .search(this.value)
            .draw();
        });

        // Clean filters inputs by double-clicking above the head
        $(document).on("dblclick",  ".ui.stackable.grid", function() {
            let inputs = document.getElementsByName("filter");
            inputs.forEach(e => {
                e.value = "";
            });
            table.search('');
            table.columns().search('').draw();
        });
		changeDatatableInputFont();
		removeSortingLabel('students-debts');
    });
</script>

{% endblock %}