rating/api/urls.py
from api import views

from django.urls import include, path

from rest_framework import routers


app_name = 'api'

router = routers.SimpleRouter()
router.register('students', views.StudentViewSet)              # [+]
router.register('results', views.ResultViewSet)                # [+]
router.register('groups', views.GroupsViewSet)                 # [+]
router.register('cathedras', views.CathedraViewSet)            # [+]
router.register('faculties', views.FacultyViewSet)             # [+]
router.register('subjects', views.SubjectViewSet)              # [+]
router.register('groupsubjects', views.GroupSubjectViewSet)    # [+]

urlpatterns = [
    path('v1/', include(router.urls)),
    path('v1/activestudents/', views.StudentsList.as_view()),            # [+]
    path('v1/history/students/', views.StudentLogList.as_view()),        # [+]
    path('v1/archivedstudents/', views.StudentsArchivedList.as_view()),  # [+]
    path('v1/studentresults/', views.ResultsForStudentList.as_view()),   # [+]
    path('v1/studentsdebts/', views.students_debts),                     # [+]
    path('v1/studentsalldebts/', views.students_all_debts),              # [+]

    path('v1/activesubjects/', views.SubjectsList.as_view()),            # [+]
    # path('v1/history/subjects/', views.SubjectLogList.as_view()),        # [-]
    path('v1/archivedsubjects/', views.SubjectsArchivedList.as_view()),  # [+]
    path('v1/archivedresults/', views.ResultsArchivedList.as_view()),    # [+]
    path('v1/subjectresults/', views.ResultsForSubjectList.as_view()),   # [+]
    path('v1/activegroupsubjects/', views.GroupSubjectsList.as_view()),  # [+]
    path('v1/money/', views.StudentMoneyList.as_view()),                 # [+]
    # path('v1/rating/', views.student_rating),  # [-]

    path('v1/resetgroupsubjects/', views.reset_groupsubjects),  # [+]

    path('v1/transfer/students/', views.transfer_students),  # [+]
    path('v1/groupmarks/', views.group_marks),               # [+]

    path('v1/import/students/', views.import_students),              # [+]
    path('v1/import/results/', views.import_results),                # [+]
    path('v1/import/cathedras/', views.import_cathedras),            # [+]
    path('v1/import/subjects/', views.import_subjects),              # [+]
    path('v1/import/groupsubjects/', views.import_groupsubjects),    # [+]
]

rating/groups/urls.py
from django.urls import path

from groups import views


app_name = 'groups'

urlpatterns = [
    path('', views.GroupView.as_view(), name='groups'),
    path('cards/', views.GroupCardsView.as_view(), name='cards'),
    path('cards/<str:groupname>-<int:semester>/', views.GroupDetailListView.as_view(), name='detail'),
]

rating/rating/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.shortcuts import render


urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/groups/cards')),
    path('archive/', include('archive.urls', namespace='archive')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('students/', include('students.urls', namespace='students')),
    path('subjects/', include('subjects.urls', namespace='subjects')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls', namespace='api')),
]


def custom_404(request, exception=None):
    return render(request, '404.html', status=404)


handler404 = custom_404

rating/groups/models.py
from django.db import models
from django.urls import reverse

from rating.abstracts import CommonArchivedModel, CommonTimestampModel


class Group(CommonTimestampModel, CommonArchivedModel):
    """Модель <Группа>."""

    class Level(models.TextChoices):
        BAC = 'Бакалавриат', 'Бакалавриат'
        MAG = 'Магистратура', 'Магистратура'

    name = models.CharField(
        verbose_name='Группа',
        max_length=20,
        unique=True,
    )
    direction = models.CharField(
        verbose_name='Направление подготовки',
        max_length=50,
    )
    profile = models.CharField(
        verbose_name='Профиль | Специализация',
        max_length=100,
        default='-',
    )
    level = models.CharField(
        verbose_name='Уровень обучения',
        choices=Level.choices,
        default=Level.BAC,
        blank=False,
        max_length=15,
    )
    code = models.CharField(
        verbose_name='Шифр направления',
        max_length=10,
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'
        ordering = [
            'level',
            'code',
            'name',
        ]


    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('groups:cards', args=[str(self.id)])

rating/groups/forms.py
import re

from django.core.exceptions import ValidationError
from django.forms import ModelForm

from groups.models import Group


class GroupForm(ModelForm):
    """Форма добавления | обновления групп."""
    class Meta:
        model = Group
        fields = [
            'name',
            'direction',
            'profile',
            'level',
            'code',
            'is_archived',
        ]

    def clean_code(self):
        """Проверить формат шифра направления."""
        code = self.cleaned_data['code']
        pattern = r'^([0-9]{2})\.([0-9]{2})\.([0-9]{2})$'

        if not re.match(pattern, code):
            raise ValidationError('Неверный формат')
        return code

rating/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, TemplateView
from django.shortcuts import get_object_or_404
from django.db.models.functions import Length

from groups.forms import GroupForm
from groups.models import Group
from students.models import Student
from subjects.models import GroupSubject


class GroupView(LoginRequiredMixin, TemplateView):
    template_name = 'groups/groups.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['groups'] = Group.objects.filter(is_archived=False).count()
        context['form'] = GroupForm()
        return context


class GroupCardsView(LoginRequiredMixin, ListView):
    """Отобразить карточки групп."""
    model = Group
    template_name = 'groups/group_cards.html'

    def get_queryset(self):
        queryset = Group.objects.filter(is_archived=False).annotate(name_length=Length('name')).values('id', 'name', 'direction', 'profile', 'level', 'code')
        queryset = queryset.order_by('direction', 'profile', 'name_length')
        return queryset


class GroupDetailListView(LoginRequiredMixin, TemplateView):
    '''Отображение студентов соответствующей группы и семестра и назначенных им дисциплин.'''
    template_name = 'groups/group_detail.html'

    def get(self, request, groupname, semester, **kwargs):
        context = self.get_context_data(**kwargs)
        # текущая группа
        group = get_object_or_404(Group, name=groupname)
        # студенты текущей группы
        students = Student.active_objects.select_related('basis', 'group').filter(
            group__name=groupname,
            semester=semester,
            status='Является студентом'
        ).order_by('last_name')
        # дисциплины, назначенные текущей группе в соответствующем семестре
        subjects = GroupSubject.active_objects.select_related('subjects').filter(
            groups__name=groupname,
            subjects__semester=semester,
        ).order_by('subjects__form_control', 'subjects__name')
        # текущий курс группы
        course = students[0].course if students else '-'

        if group.level == 'Бакалавриат':
            if 'Сб(ИС)' in group.name:
                max_semester = 6
                min_semester = 1
            elif 'Сб(ИС-' in group.name:
                max_semester = 8
                min_semester = 7
            else:
                max_semester = 8
                min_semester = 1
        else:
            max_semester = 4
            min_semester = 1

        previous_semester = semester - 1 if semester > min_semester else False
        next_semester = semester + 1 if semester < max_semester else False

        # профильные группы строительства
        groups = Group.objects.filter(is_archived=False, name__contains='Сб(ИС-')

        context = {
            'students': students,
            'subjects': subjects,
            'group': group,
            'groups': groups,
            'semester': semester,
            'course': course,
            'previous_semester': previous_semester,
            'next_semester': next_semester,
        }
        return self.render_to_response(context)

rating/groups/templates/groups/group_cards.html
<!DOCTYPE html>

{% extends "base.html" %}

{% load static %}

{% block title %}Карточки групп{% endblock %}

{% block content %}

<div id="groupcards" class="ui basic segment">
   <div class="ui equal width center aligned padded grid">
      <div class="column">
         <h2 class="ui header center aligned" style="font-family: Hack"><i class="graduation cap grey icon"></i>Бакалавриат</h2>
         <div class="ui hidden divider"></div>
         <!-- Bachelor -->
         <!-- Cards -->
         <div class="ui cards">
            {% for group in group_list %}
               {% if group.level == 'Бакалавриат' %}
                  <!-- Card -->
                  <div id="group-cards" class="ui card" style="width: 200px; margin-left: 35px">
                     <div class="content">
                        <!-- Link button to group -->
                        <div class="header left aligned">
                           <button id="group-label"
                              onclick="showGroupInfo('{{ group.code }}', '{{ group.direction }}', '{{ group.profile }}')"
                              type="button"
                              class="fluid ui green small circular button" style="font-family: Hack">
                              {% if group.is_archived %}<i class="archive yellow icon"></i>{% endif %}
                              {{ group.name }}
                           </button>
                        </div>

                        <div class="ui horizontal divider">Семестр</div>

                        {% csrf_token %}
                        <!-- Semesters -->
                        <div class="extra content">

                           <div class="ui grid">
                              <div class="row">
                                 <div class="column" style="padding-left: 0; padding-right: 0">
                                    <button class="ui small circular basic button" style="font-family: Hack; width: 35px; padding-left: 0; padding-right: 0" name="semester" id="1" onclick="window.location.href = '{% url 'groups:detail' groupname=group.name semester=1 %}';">1</button>
                                    <button class="ui small circular basic button" style="font-family: Hack; width: 35px; padding-left: 0; padding-right: 0" name="semester" id="3" onclick="window.location.href = '{% url 'groups:detail' groupname=group.name semester=3 %}';">3</button>
                                    <button class="ui small circular basic button" style="font-family: Hack; width: 35px; padding-left: 0; padding-right: 0" name="semester" id="5" onclick="window.location.href = '{% url 'groups:detail' groupname=group.name semester=5 %}';">5</button>
                                    <button class="ui small circular basic button" style="font-family: Hack; width: 35px; padding-left: 0; padding-right: 0" name="semester" id="7" onclick="window.location.href = '{% url 'groups:detail' groupname=group.name semester=7 %}';">7</button>
                                 </div>
                              </div>
                              <div class="row" style="padding-top: 7px">
                                 <div class="column" style="padding-left: 0; padding-right: 0">
                                    <button class="ui small circular basic button" style="font-family: Hack; width: 35px; padding-left: 0; padding-right: 0" name="semester" id="2" onclick="window.location.href = '{% url 'groups:detail' groupname=group.name semester=2 %}';">2</button>
                                    <button class="ui small circular basic button" style="font-family: Hack; width: 35px; padding-left: 0; padding-right: 0" name="semester" id="4" onclick="window.location.href = '{% url 'groups:detail' groupname=group.name semester=4 %}';">4</button>
                                    <button class="ui small circular basic button" style="font-family: Hack; width: 35px; padding-left: 0; padding-right: 0" name="semester" id="6" onclick="window.location.href = '{% url 'groups:detail' groupname=group.name semester=6 %}';">6</button>
                                    <button class="ui small circular basic button" style="font-family: Hack; width: 35px; padding-left: 0; padding-right: 0" name="semester" id="8" onclick="window.location.href = '{% url 'groups:detail' groupname=group.name semester=8 %}';">8</button>
                                 </div>
                              </div>
                           </div>

                        </div>
                     </div>
                  </div>
               {% endif %}
            {% endfor %}
         </div>
      </div>


      <div class="column">
         <h2 class="ui header center aligned" style="font-family: Hack"><i class="graduation cap grey icon"></i>Магистратура</h2>
         <div class="ui hidden divider"></div>
         <!-- Cards -->
         <div class="ui three cards">
            {% for group in group_list %}
               {% if group.level == 'Магистратура' %}

                  <!-- Card -->
                  <div id="group-cards" class="ui card" style="width: 200px; margin-left: 35px">
                     <div class="content">
                        <!-- Link button to group -->
                        <div class="header left aligned">
                           <button id="group-label"
                              onclick="showGroupInfo('{{ group.code }}', '{{ group.direction }}', '{{ group.profile }}')"
                              type="button"
                              class="fluid ui blue small circular button" style="font-family: Hack">
                              {% if group.is_archived %}<i class="archive yellow icon"></i>{% endif %}
                              {{ group.name }}
                           </button>
                        </div>

                        <div class="ui horizontal divider">Семестр</div>

                        {% csrf_token %}
                        <!-- Semesters -->
                        <div class="extra content">

                           <div class="ui grid">
                              <div class="row">
                                 <div class="column" style="padding-left: 0; padding-right: 0">
                                    <button class="ui small circular basic button" style="font-family: Hack; width: 35px; padding-left: 0; padding-right: 0" name="semester" id="1" onclick="window.location.href = '{% url 'groups:detail' groupname=group.name semester=1 %}';">1</button>
                                    <button class="ui small circular basic button" style="font-family: Hack; width: 35px; padding-left: 0; padding-right: 0" name="semester" id="2" onclick="window.location.href = '{% url 'groups:detail' groupname=group.name semester=2 %}';">2</button>
                                    <button class="ui small circular basic button" style="font-family: Hack; width: 35px; padding-left: 0; padding-right: 0" name="semester" id="3" onclick="window.location.href = '{% url 'groups:detail' groupname=group.name semester=3 %}';">3</button>
                                    <button class="ui small circular basic button" style="font-family: Hack; width: 35px; padding-left: 0; padding-right: 0" name="semester" id="4" onclick="window.location.href = '{% url 'groups:detail' groupname=group.name semester=4 %}';">4</button>
                                 </div>
                              </div>
                           </div>

                        </div>
                     </div>
                  </div>

               {% endif %}
            {% endfor %}
         </div>
      </div>
   </div>
</div>

<!-- Modal with group info -->
<div id="group-info" class="ui tiny modal">
   <div class="basic center aligned header" style="font-family: Hack">Информация о группе</div>
   <div id="modal-content" class="content" style="font-family: Hack"></div>
</div>


<script type="text/javascript">
   // подсветка текущих семестров
   $(document).ready(function() {
      var currentMonth = new Date().getMonth() + 1;

      autumn = [9, 10, 11, 12, 1];  // odd
      spring = [2, 3, 4, 5, 6, 7, 8];  // even

      semesterButtons = document.getElementsByName("semester");

      if(autumn.includes(currentMonth)) {
         semesterButtons.forEach(element => {
            num = parseInt(element.id) % 2;
            if(num == 1) {
               element.classList.add("grey");
               element.classList.remove("basic");
            };
         });
      } else if(spring.includes(currentMonth)) {
         semesterButtons.forEach(element => {
            num = parseInt(element.id) % 2;
            if(num == 0) {
               element.classList.add("grey");
               element.classList.remove("basic");
            };
         });
      };
   });

   // всплывающие окна с информацией о шифре, направлении, профиле группы
   function showGroupInfo(code, direction, profile) {
      var element = document.getElementById('group-info');
      $(element).modal({blurring: true}).modal('show');
      var content = document.getElementById('modal-content');

      content.innerHTML = `
         <p>${code}</p>
         <p>${direction}</p>
         <p>${profile}</p>
      `;
   };
   
</script>

{% endblock %}

rating/groups/templates/groups/groups.html
{% extends "base.html" %}

{% load static %}

{% load semanticui %}

{% load customfilters %}

{% block title %}Группы{% endblock %}

{% block content %}

<div id="has-group" style="display: none">{{ request.user|has_group:"Сотрудники" }}</div>
<div id="segments" class="ui basic segments">

    <!-- Title & button -->
    <div class="ui basic segment">
        <div class="ui stackable two column grid">
            <div class="column"><h2 style="font-family: Hack">Группы</h2></div>
            <div class="column right aligned">
                {% if request.user|has_group:"Сотрудники" %}
                    <button id="add-button" class="ui positive small circular button" onclick="showModal('add-modal')"><i class="icon plus circle"></i>Добавить</button>
                {% endif %}
            </div>
        </div>
    </div>
    
    <!-- Table -->
    <div id="datatable-segment" class="ui basic segment">
        {% if groups %}
            <table id="groups-table" class="ui selectable compact celled table">
                <!-- data from script -->
            </table>
        {% else %}
            {% include 'empty_records.html' %}
        {% endif %}
    </div>
</div>

<!-- Modal for add group -->
<div id="add-modal" class="ui large modal">
    <div class="basic center aligned header" style="font-family: Hack">Добавить группу</div>
    <div class="content" style="font-family: Hack">
        <form id="add-form" method="POST">
            {% csrf_token %}
            <div class="ui form">
                <div class="required field">
                    <label>Название</label>
                    {{ form.name }}
                </div>
                <div class="two fields">
                    <div class="required field">
                        <label>Направление</label>
                        {{ form.direction }}
                    </div>
                    <div class="required field">
                        <label>Профиль | Специализация</label>
                        {{ form.profile }}
                    </div>
                </div>
                <div class="two fields">
                    <div class="required field">
                        <label>Уровень обучения</label>
                        {% render_field form.level _no_label='True' placeholder='Выбрать' %}
                    </div>
                    <div class="required field {% if form.code.errors %} error {% endif %}">
                        <label>Шифр в формате: XX.XX.XX</label>
                        {{ form.code }}
                    </div>
                </div>
                <div class=" field">
                    {% render_field form.is_archived %}
                </div>
            </div>
        </form>
    </div>
    <div class="basic actions">
        <div class="ui circular cancel button" onclick="resetAddForm()" style="font-family: Hack"><i class="times circle icon"></i>Отмена</div>
        <div class="ui green circular button" onclick="saveGroupForm()" style="font-family: Hack"><i class="save icon"></i>Сохранить</div>
    </div>
</div>

<!-- Modal for update group -->
<div id="group-update-modal" class="ui large modal">
    <div class="basic center aligned header" style="font-family: Hack">Изменить группу</div>
    <div class="content" style="font-family: Hack">
        <form id="group-update-form" method="POST">
            {% csrf_token %}
            <div class="ui form">
                <div class="required field">
                    <label>Название</label>
                    {{ form.name }}
                </div>
                <div class="two fields">
                    <div class="five wide required field">
                        <label>Направление</label>
                        {{ form.direction }}
                    </div>
                    <div class="eleven wide required field">
                        <label>Профиль | Специализация</label>
                        {{ form.profile }}
                    </div>
                </div>
                <div class="two fields">
                    <div class="required field">
                        <label>Уровень обучения</label>
                        {% render_field form.level _no_label='True' placeholder='Выбрать' %}
                    </div>
                    <div class="required field {% if form.code.errors %} error {% endif %}">
                        <label>Шифр в формате: XX.XX.XX</label>
                        {{ form.code }}
                    </div>
                </div>
                <div class=" field">
                    {% render_field form.is_archived %}
                </div>
            </div>
        </form>
    </div>
    <div class="basic actions">
        <div class="ui circular cancel button" style="font-family: Hack"><i class="times circle icon"></i>Отмена</div>
        <div id="update-btn" class="ui blue circular button" onclick="updateGroup()" style="font-family: Hack"><i class="sync alternate icon"></i>Изменить</div>
    </div>
</div>

<!-- Modal for delete group -->
<div id="group-delete-modal" class="ui modal">
    <div class="basic center aligned header" style="font-family: Hack">Удалить группу</div>
    <div class="content" style="font-family: Hack">
        <table class="ui definition table" style="margin-top: 0">
            <tbody>
                <tr>
                    <td class="five wide">Название</td>
                    <td id="del-name"></td>
                </tr>
                <tr>
                    <td>Направление</td>
                    <td id="del-direction"></td>
                </tr>
                <tr>
                    <td>Профиль | Специализация</td>
                    <td id="del-profile"></td>
                </tr>
                <tr>
                    <td>Уровень обучения</td>
                    <td id="del-level"></td>
                </tr>
                <tr>
                    <td>Шифр</td>
                    <td id="del-code"></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="basic actions">
        <div class="ui circular cancel button" style="font-family: Hack"><i class="times circle icon"></i>Отмена</div>
        <div id="delete-btn" class="ui red circular button" onclick="deleteGroup()" style="font-family: Hack"><i class="trash alternate outline icon"></i>Удалить</div>
    </div>
</div>

<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
<script type="text/javascript" src="{% static 'js/script_groups.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        if ($.fn.DataTable.isDataTable('#groups-table')) {
            $('#groups-table').DataTable().destroy();
        };

        const dataTableOptions = {
            columns: [
                { title: '<i class="hashtag small icon"></i>' },
                { title: 'Название' },
                { title: 'Уровень' },
                { title: 'Направление' },
                { title: 'Профиль | Специализация' },
                { title: 'Шифр' },
                { title: 'Удалить', orderable: false },
                { title: 'Изменить', orderable: false },
            ],
            language: {
                zeroRecords: 'Записей нет...',
                info: 'Всего записей: _MAX_',
                infoEmpty: '',
                infoFiltered: 'Найдено: _TOTAL_',
                search: '',
                searchPlaceholder: 'поиск',
            },
            paging: false,
            searching: true,
            ordering: true,
            autoWidth: false,
            columnDefs: [
                { width: "3%", targets: [0, 6, 7] },
                { width: "10%", targets: [1, 2] },
                { width: "24%", targets: 3 },
                { width: "42%", targets: 4 },
                { width: "5%", targets: 5 },
                { orderable: false, targets: [6, 7] },
                { className: 'center aligned', targets: [0, 1, 2, 5, 6, 7] },
            ],
            headerCallback: function(thead, data, start, end, display) {
                $(thead).find('th').addClass('center aligned');
            },
        };

        $('#groups-table').DataTable(dataTableOptions);

        var forms = document.forms;
        for (let i = 0; i < forms.length; i++) {
            var formElements = forms[i].elements;
            for (let j = 0; j < formElements.length; j++) {
                if (formElements[j].localName == "input" && formElements[j].type == "text") {
                    formElements[j].style.fontFamily = "Hack";
                };
            };
        };
        changeDatatableInputFont();
        deletePaddingTopForDatatableSegment();
    });
</script>
{% endblock %}