rating/api/urls.py
from api import views

from django.urls import include, path

from rest_framework import routers


app_name = 'api'

router = routers.SimpleRouter()
router.register('students', views.StudentViewSet)              # [+]
router.register('results', views.ResultViewSet)                # [+]
router.register('groups', views.GroupsViewSet)                 # [+]
router.register('cathedras', views.CathedraViewSet)            # [+]
router.register('faculties', views.FacultyViewSet)             # [+]
router.register('subjects', views.SubjectViewSet)              # [+]
router.register('groupsubjects', views.GroupSubjectViewSet)    # [+]

urlpatterns = [
    path('v1/', include(router.urls)),
    path('v1/activestudents/', views.StudentsList.as_view()),            # [+]
    path('v1/history/students/', views.StudentLogList.as_view()),        # [+]
    path('v1/archivedstudents/', views.StudentsArchivedList.as_view()),  # [+]
    path('v1/studentresults/', views.ResultsForStudentList.as_view()),   # [+]
    path('v1/studentsdebts/', views.students_debts),                     # [+]
    path('v1/studentsalldebts/', views.students_all_debts),              # [+]

    path('v1/activesubjects/', views.SubjectsList.as_view()),            # [+]
    # path('v1/history/subjects/', views.SubjectLogList.as_view()),        # [-]
    path('v1/archivedsubjects/', views.SubjectsArchivedList.as_view()),  # [+]
    path('v1/archivedresults/', views.ResultsArchivedList.as_view()),    # [+]
    path('v1/subjectresults/', views.ResultsForSubjectList.as_view()),   # [+]
    path('v1/activegroupsubjects/', views.GroupSubjectsList.as_view()),  # [+]
    path('v1/money/', views.StudentMoneyList.as_view()),                 # [+]
    # path('v1/rating/', views.student_rating),  # [-]

    path('v1/resetgroupsubjects/', views.reset_groupsubjects),  # [+]

    path('v1/transfer/students/', views.transfer_students),  # [+]
    path('v1/groupmarks/', views.group_marks),               # [+]

    path('v1/import/students/', views.import_students),              # [+]
    path('v1/import/results/', views.import_results),                # [+]
    path('v1/import/cathedras/', views.import_cathedras),            # [+]
    path('v1/import/subjects/', views.import_subjects),              # [+]
    path('v1/import/groupsubjects/', views.import_groupsubjects),    # [+]
]

rating/rating/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.shortcuts import render


urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/groups/cards')),
    path('archive/', include('archive.urls', namespace='archive')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('students/', include('students.urls', namespace='students')),
    path('subjects/', include('subjects.urls', namespace='subjects')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls', namespace='api')),
]


def custom_404(request, exception=None):
    return render(request, '404.html', status=404)


handler404 = custom_404

rating/subjects/urls.py
from django.urls import path

from subjects import views


app_name = 'subjects'

urlpatterns = [
    path('', views.SubjectView.as_view(), name='subjects'),
    path('<int:pk>/', views.SubjectDetailView.as_view(), name='detail'),
    path('debts/', views.SubjectsDebtsListView.as_view(), name='debts'),
    path('faculties/', views.FacultyView.as_view(), name='faculties'),
    path('cathedras/', views.CathedraView.as_view(), name='cathedras'),
    path('groupsubjects/', views.GroupSubjectView.as_view(), name='groupsubjects'),
]

rating/subjects/models.py
from django.db import models
from django.urls import reverse

from rating.abstracts import CommonArchivedModel, CommonModelLog, CommonTimestampModel


class ArchivedSubjectManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_archived=True)


class ActiveSubjectManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_archived=False)


class Subject(CommonArchivedModel, CommonTimestampModel):
    objects = models.Manager()
    archived_objects = ArchivedSubjectManager()
    active_objects = ActiveSubjectManager()

    class Formcontrol(models.TextChoices):
        EXAM = 'Экзамен', 'Экзамен'
        DIF = 'Диффзачет', 'Диффзачет'
        ZACH = 'Зачет', 'Зачет'
        KP = 'Курсовой проект', 'Курсовой проект'
        KR = 'Курсовая работа', 'Курсовая работа'


    name = models.CharField(
        verbose_name='Дисциплина',
        max_length=150,
        blank=False,
        unique=False,
        db_index=True,
    )
    form_control = models.CharField(
        verbose_name='Форма контроля',
        choices=Formcontrol.choices,
        blank=False,
        max_length=15,
    )
    semester = models.ForeignKey(
        'students.Semester',
        on_delete=models.PROTECT,
        verbose_name='Семестр',
        blank=False,
    )
    cathedra = models.ForeignKey(
        'subjects.Cathedra',
        on_delete=models.PROTECT,
        blank=False,
        verbose_name='Кафедра',
    )
    zet = models.CharField(
        verbose_name='ЗЕТ',
        help_text='72 (2)',
        max_length=15,
        blank=True,
        default='',
        unique=False,
    )
    comment = models.CharField(
        verbose_name='Примечание',
        max_length=255,
        blank=True,
        unique=False,
        default='',
    )

    class Meta:
        verbose_name = 'Дисциплины'
        verbose_name_plural = 'Дисциплины'
        ordering = [
            'name',
            'semester',
            '-form_control',
            'cathedra',
        ]
        unique_together = (
            ('name', 'form_control', 'semester', 'cathedra'),
        )


    def __str__(self):
        if self.cathedra is None:
            return f'{self.name} | {self.form_control} | {self.semester} семестр | ***'
        else:
            return f'{self.name} | {self.form_control} | {self.semester} семестр | {self.cathedra.short_name}'

    def save(self, *args, **kwargs):
        # Checking if the object is exist
        if Subject.objects.filter(id=self.pk).exists():
            if self.pk is not None:
                # Changing the model
                old = Subject.objects.get(pk=self.pk)
                # Getting all model fields
                field_names = [field.name for field in Subject._meta.fields]
                # Preparing a dict for changes
                update_fields = {}
                for field_name in field_names:
                    try:
                        if getattr(old, field_name) != getattr(self, field_name):
                            update_fields[field_name] = (
                                getattr(old, field_name), getattr(self, field_name))
                            update_fields['id'] = self.id
                    except Exception as ex:
                        print('[!] ---> Ошибка лога Subject', ex)
            # Adding records to table
            try:
                for key in update_fields:
                    if key != 'id':
                        SubjectLog.objects.create(
                            field=Subject._meta.get_field(key).verbose_name,
                            old_value=update_fields[key][0],
                            new_value=update_fields[key][1],
                            record_id=update_fields['id'],
                        )
            except Exception as subject_log_ex:
                print(f'Не удалось записать изменения по дисциплинам:')
                print('[!] ---> Ошибка:', subject_log_ex)

        # Change ZET field for KP, KR form controls
        match self.form_control:
            case 'Курсовая работа':
                self.zet = 'КР'
            case 'Курсовой проект':
                self.zet = 'КП'

        super(Subject, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('subjects:detail', args=[str(self.id)])

    @property
    def empty_cathedra(self):
        """Return <Нет>, if a cathedra is empty."""
        if not self.cathedra:
            return 'Нет'
        else:
            return self.cathedra

    @property
    def empty_zet(self):
        """Return <Нет>, if a ZET is empty."""
        if not self.zet:
            return 'Нет'
        else:
            return self.zet


class SubjectLog(CommonModelLog):
    class Meta:
        verbose_name = 'Изменения в дисциплинах'
        verbose_name_plural = "Изменения в дисциплинах"
        ordering = [
            '-timestamp',
        ]

    def __str__(self):
        return f'{self.id}'


class ArchivedGroupSubjectManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_archived=True)


class ActiveGroupSubjectManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_archived=False)


class GroupSubject(CommonArchivedModel, CommonTimestampModel):
    objects = models.Manager()
    archived_objects = ArchivedGroupSubjectManager()
    active_objects = ActiveGroupSubjectManager()

    groups = models.ForeignKey(
        'groups.Group',
        on_delete=models.CASCADE,
        verbose_name='Группа',
    )
    subjects = models.ForeignKey(
        'subjects.Subject',
        on_delete=models.CASCADE,
        verbose_name='Дисциплина',
        db_index=True,
    )
    teacher = models.CharField(
        verbose_name='Преподаватель',
        help_text='Фамилия И.О.',
        max_length=150,
        blank=True,
        default='',
        unique=False,
        db_index=True,
    )
    att_date = models.DateField(
        verbose_name='Дата аттестации',
        auto_now=False,
        auto_now_add=False,
        unique=False,
        blank=True,
        null=True,
    )
    comment = models.CharField(
        verbose_name='Примечание',
        max_length=255,
        blank=True,
        unique=False,
        default='',
        db_index=True,
    )

    class Meta:
        verbose_name = 'Назначения дисциплин'
        verbose_name_plural = 'Назначения дисциплин'
        ordering = [
            'groups_id',
            'subjects',
            '-att_date',
        ]

    def __str__(self):
        if self.teacher and not self.att_date:
            return f'{self.subjects} | {self.groups} | {self.teacher}'
        elif not self.teacher and self.att_date:
            return f'{self.subjects} | {self.groups} | {self.att_date}'
        elif not self.teacher and not self.att_date:
            return f'{self.subjects} | {self.groups}'
        else:
            return f'{self.subjects} | {self.groups} | {self.teacher} | {self.att_date}'

    def get_absolute_url(self):
        return reverse('subjects:groupsubject_update', args=[str(self.id)])

    @property
    def empty_att_date(self):
        """Create a note, if an att date is empty."""
        if self.att_date == None or self.att_date == "":
            return 'Нет'
        else:
            return self.att_date

    @property
    def empty_teacher(self):
        """Create a note, if a teacher's full name is empty."""
        if self.teacher == '':
            return 'Нет'
        else:
            return f'{self.teacher}'


class Cathedra(CommonTimestampModel):
    name = models.CharField(
        verbose_name='Кафедра',
        max_length=255,
        unique=True,
    )
    short_name = models.CharField(
        verbose_name='Сокращение',
        max_length=10,
        blank=True,
        default='',
    )
    faculty = models.ForeignKey(
        'subjects.Faculty',
        on_delete=models.SET_NULL,
        verbose_name='Факультет',
        blank=True,
        default='',
        null=True,
    )

    class Meta:
        verbose_name = 'Кафедры'
        verbose_name_plural = 'Кафедры'
        ordering = [
            'name',
        ]
        unique_together = (
            ('name', 'short_name', 'faculty'),
        )

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('subjects:cathedra_update', args=[str(self.id)])

    @property
    def empty_short_name(self):
        """Return <Нет>, if a cathedra's short name is empty."""
        if self.short_name == None:
            return 'Нет'
        else:
            return self.short_name

    @property
    def empty_faculty(self):
        """Return <Нет>, if a cathedra's faculty is empty."""
        if self.faculty == None:
            return 'Нет'
        else:
            return self.faculty


class Faculty(CommonTimestampModel):
    name = models.CharField(
        verbose_name='Полное название факультета',
        max_length=255,
    )
    short_name = models.CharField(
        verbose_name='Сокращение (аббревиатура)',
        max_length=10,
    )

    class Meta:
        verbose_name = 'Факультеты'
        verbose_name_plural = 'Факультеты'
        ordering = [
            'name',
        ]

    def __str__(self):
        return f'{self.name}'

rating/subjects/forms.py
import datetime
import re

from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.forms.widgets import DateInput, TextInput, Input

from groups.models import Group
from subjects.models import Cathedra, Faculty, GroupSubject, Subject


class SubjectForm(ModelForm):
    class Meta:
        model = Subject
        fields = [
            'name',
            'cathedra',
            'form_control',
            'zet',
            'semester',
            'comment',
            'is_archived',
        ]

    def clean_zet(self):
        """Check ZET format."""
        zet = self.cleaned_data['zet']
        form_control = self.cleaned_data['form_control']
        pattern1 = r'^([0-9]{2,3})\s\(([0-9]{1,2})\)$'  # 72 (2)
        pattern2 = r'^(КР|КП)$'  # КР or КП

        if not zet:
            return zet
        elif form_control in [Subject.Formcontrol.KP, Subject.Formcontrol.KR]:
            if not re.match(pattern2, zet):
                raise ValidationError('Неверный формат ЗЕТ')
            else:
                return zet
        elif not re.match(pattern1, zet):
            raise ValidationError('Неверный формат ЗЕТ')
        else:
            return zet


class FacultyForm(ModelForm):
    class Meta:
        model = Faculty
        fields = [
            'name',
            'short_name',
        ]


class CathedraForm(ModelForm):
    class Meta:
        model = Cathedra
        fields = [
            'name',
            'short_name',
            'faculty',
        ]
        widgets = {
            'name': TextInput(
                attrs={'placeholder': 'без слова <кафедра>'},
            ),
            'short_name': TextInput(
                attrs={'placeholder': 'пример: КСФиХ'},
            ),
        }


class GroupSubjectForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(GroupSubjectForm, self).__init__(*args, **kwargs)
        self.fields['groups'].queryset = Group.objects.filter(is_archived=False)
        self.fields['subjects'].queryset = Subject.active_objects.order_by('semester')

    subjects = Input()

    class Meta:
        model = GroupSubject
        fields = [
            'groups',
            'subjects',
            'teacher',
            'att_date',
            'comment',
            'is_archived',
        ]
        widgets = {
            'att_date': DateInput(
                attrs={'placeholder': '24.06.1999'},
                format='%d.%m.%Y',
            ),
            'teacher': TextInput(
                attrs={'placeholder': 'Формат: Иванов И.И., Петров П.П.'},
            ),
        }

    def clean_teacher(self):
        """Check teacher full name."""
        raw_teachers = self.cleaned_data['teacher']
        if not raw_teachers:
            return ''
        else:
            teachers = check_teachers_name(raw_teachers)

        if teachers:
            return teachers
        else:
            raise ValidationError('Неверный формат ФИО')

    def clean_att_date(self):
        """Check date format."""
        date = self.cleaned_data['att_date']
        pattern = r'^([0-9]{2})\.([0-9]{2})\.([0-9]{4})$'  # DD.MM.YYYY

        if not date or isinstance(date, datetime.date):
            return date
        elif not re.match(pattern, date):
            raise ValidationError('Неверный формат даты')
        else:
            return date


def check_teachers_name(names: list):
    """Validate teacher's full name."""
    pattern_1 = r'^(\w{1,})\s(\w{1})\.(\w{1})\.$'  # Фамилия И.О.
    pattern_2 = r'^(\w{1,})-(\w{1,})\s(\w{1})\.(\w{1})\.$'  # Фамилия-Фамилия И.О.
    teachers = []
    raw_teachers = names.split(', ')

    if len(raw_teachers) == 1:  # ['Фамилия И.О.']
        teacher = raw_teachers[0]
        if not teacher:
            return False
        elif re.match(pattern_1, teacher) or re.match(pattern_2, teacher):
            return teacher
        else:
            return False
    else:
        for name in raw_teachers:  # ['Фамилия1 И.О.', 'Фамилия1 И.О.']
            if not re.match(pattern_1, name) or re.match(pattern_2, name):
                return False
            else:
                teachers.append(name)
        return ', '.join(teachers)

rating/subjects/templates/subjects/faculties.html
{% extends "base.html" %}

{% load static %}

{% load customfilters %}

{% block title %}Факультеты{% endblock %}

{% block content %}

<div id="has-group" style="display: none">{{ request.user|has_group:"Сотрудники" }}</div>
<div id="segments" class="ui basic segments">

    <!-- Title & button -->
    <div class="ui basic segment">
        <div class="ui stackable two column grid">
            <div class="column"><h2 style="font-family: Hack">Факультеты</h2></div>
            <div class="column right aligned">
                {% if request.user|has_group:"Сотрудники" %}
                    <button id="add-button" class="ui positive small circular button" onclick="showModal('add-modal')"><i class="icon plus circle"></i>Добавить</button>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Table -->
    <div id="datatable-segment" class="ui basic segment">
        {% if faculties %}
            <table id="faculties-table" class="ui selectable celled compact table">
                <thead>
                    <tr class="center aligned">
                        <th class="collapsing"><i class="hashtag small icon"></i></th>
                        <th class="collapsing">Сокращение</th>
                        <th>Полное название</th>
                        <th class="collapsing">Удалить</th>
                        <th class="collapsing">Изменить</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- data from script -->
                </tbody>
            </table>
        {% else %}
            {% include 'empty_records.html' %}
        {% endif %}
    </div>
</div>

<!-- Modal for add faculty -->
<div id="add-modal" class="ui modal">
    <div class="basic center aligned header" style="font-family: Hack">Добавить факультет</div>
    <div class="content" style="font-family: Hack">
        <form id="add-form" method="POST">
            {% csrf_token %}
            <div class="ui large form">
                <div class="required field">
                    <label>Полное название</label>
                    {{ form.name }}
                </div>
                <div class="required field">
                    <label>Сокращенние [аббревиатура]</label>
                    {{ form.short_name }}
                </div>
            </div>
        </form>
    </div>
    <div class="basic actions">
        <div class="ui circular cancel button" onclick="resetAddForm()" style="font-family: Hack"><i class="times circle icon"></i>Отмена</div>
        <div class="ui green circular button" onclick="saveFacultyForm()" style="font-family: Hack"><i class="save icon"></i>Сохранить</div>
    </div>
</div>

<!-- Modal for update faculty -->
<div id="update-modal" class="ui modal">
    <div class="basic center aligned header" style="font-family: Hack">Изменить факультет</div>
    <div class="content" style="font-family: Hack">
        <form id="update-form" method="POST">
            {% csrf_token %}
            <div class="ui large form">
                <div class="required field">
                    <label>Полное название</label>
                    {{ form.name }}
                </div>

                <div class="required field">
                    <label>Сокращение [аббревиатура]</label>
                    {{ form.short_name }}
                </div>
            </div>
        </form>
    </div>
    <div class="basic actions">
        <div class="ui circular cancel button" style="font-family: Hack"><i class="times circle icon"></i>Отмена</div>
        <div id="update-btn" class="ui blue circular button" onclick="updateFaculty()" style="font-family: Hack"><i class="sync alternate icon"></i>Изменить</div>
    </div>
</div>

<!-- Modal for delete faculty -->
<div id="delete-modal" class="ui modal">
    <div class="basic center aligned header" style="font-family: Hack">Удалить факультет</div>
    <div class="content" style="font-family: Hack">
        <h4 id="del-info" style="font-family: Hack"></h4>
    </div>
    <div class="basic actions">
        <div class="ui circular cancel button" style="font-family: Hack"><i class="times circle icon"></i>Отмена</div>
        <div id="delete-btn" class="ui red circular button" onclick="deleteFaculty()" style="font-family: Hack"><i class="trash alternate outline icon"></i>Удалить</div>
    </div>
</div>

<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
<script type="text/javascript" src="{% static 'js/script_faculties.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        var forms = document.forms;
        for (let i = 0; i < forms.length; i++) {
            var formElements = forms[i].elements;
            for (let j = 0; j < formElements.length; j++) {
                if (formElements[j].localName == "input" && formElements[j].type == "text") {
                    formElements[j].style.fontFamily = "Hack";
                };
            };
        };
    });
</script>
{% endblock %}

rating/subjects/templates/subjects/subjects_debts.html
<!DOCTYPE html>

{% extends "base.html" %}

{% load static %}

{% block title %}Текущие задолженности по дисциплинам{% endblock %}

{% block content %}

<div id="segments" class="ui basic segments">

   <!-- Title & button -->
   <div class="ui basic segment">
      <div class="ui stackable two column grid">
         <div class="column"><h2 style="font-family: Hack">Текущие задолженности по дисциплинам</h2></div>
      </div>
   </div>

	<!-- Table -->
   <div id="datatable-segment" class="ui basic segment">
      
		{% if groupsubject_list %}
         <table id="subjects-debts" class="ui selectable celled compact small table">

            <thead>
               <tr class="center aligned">
                  <th id="numbers" class="collapsing"><i class="hashtag small icon"></i></th>
                  <th class="collapsing">Кафедра</th>
                  <th class="collapsing">Название</th>
                  <th class="collapsing" style="width: 50px">Форма контроля</th>
                  <th class="collapsing">Группа</th>
                  <th class="collapsing">Семестр</th>
                  <th class="collapsing">Преподаватель</th>
                  <th class="collapsing">Сессия</th>
                  <th class="collapsing">Пересдача</th>
                  <th class="collapsing">Комиссия</th>
               </tr>
            </thead>

            <tbody>
               {% for item in groupsubject_list %}
                  <tr>
                     <td class="collapsing center aligned">{{ forloop.counter }}</td>
                     <td class="collapsing center aligned">{{ item.subjects.cathedra.short_name }}</td>
                     <td class="collapsing">
                        <a href="{{ item.subjects.get_absolute_url }}">{{ item.subjects.name|truncatechars:50 }}</a>
                     </td>
                     <td class="collapsing">{{ item.subjects.form_control }}</td>
                     <td class="collapsing center aligned">
                        <a href="{% url 'groups:detail' groupname=item.groups.name semester=item.subjects.semester.semester %}">
                           {{ item.groups.name }}
                        </a>
                     </td>
                     <td class="collapsing center aligned">{{ item.subjects.semester.semester }}</td>

                     {% if item.teacher %}
                        <td class="collapsing">{{ item.teacher }}</td>
                     {% else %}
                        <td class="negative collapsing center aligned"><i class="icon close"></i>
                           {{ item.empty_teacher }}
                        </td>
                     {% endif %}

                     <td class="collapsing center aligned" style="width: 80px">
                        {% if item.att1 == 0 %}
                           <div id="att-label" class="ui red tiny label">{{ item.att1 }}</div>
                        {% else %}
                           <div id="att-label" class="ui grey tiny label">{{ item.att1 }}</div>
                        {% endif %}
                     </td>

                     <td class="collapsing center aligned" style="width: 80px">
                        {% if item.att2 %}
                           <div id="att-label" class="ui grey tiny label">{{ item.att2 }}</div>
                        {% else %}
                           {{ item.att2|default:"" }}
                        {% endif %}
                     </td>

                     <td class="collapsing center aligned" style="width: 80px">
                        {% if item.att3 %}
                           <div id="att-label" class="ui red tiny label">{{ item.att3 }}</div>
                        {% else %}
                           {{ item.att3|default:"" }}
                        {% endif %}
                     </td>
                  </tr>
               {% endfor %}
            </tbody>

         </table>
      {% else %}
			{% include 'empty_records.html' %}
		{% endif %}
   </div>
</div>

<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
<script>
   // DataTables
   $(document).ready(function() {
      document.querySelector('#subjects-debts').style.width = "100%";
      // DataTable
      var table = $('#subjects-debts').DataTable({
         language: {
            lengthMenu: '_MENU_ записей на страницу',
            zeroRecords: 'Записей нет...',
            info: 'Всего записей: _MAX_',
            infoEmpty: '',
            infoFiltered: 'Найдено: _TOTAL_',
            search: '',
            searchPlaceholder: 'поиск',
            paginate: {
               first:    '«',
               previous: '‹',
               next:     '›',
               last:     '»'
            }
         },
         lengthMenu: [
            [20, 50, -1],
            [20, 50, 'Все']
         ],
         pageLength: 20,
         autoWidth: false,
         columnDefs: [
            { width: '8%', targets: 0 },
            { width: '12%', targets: 2 },
            { width: '10%', targets: [1, 3, 4, 5, 6] },
            { width: '8%', targets: [7, 8, 9] },
         ],
      });

      let firstRow = $('#subjects-debts thead tr')[0];
		let secondRow = firstRow.cloneNode(true);
		firstRow.after(secondRow);

		let filterColumns = $('#subjects-debts thead tr')[1].children;
		for (let i = 0; i < filterColumns.length; i++) {
			let inputWidth = filterColumns[i].offsetWidth - 60;
			if(i != 0) {
				filterColumns[i].innerHTML = `
												<div class="ui input">
													<input name="filter" type="text" style="width: ${inputWidth}px" data-index=${i}>
												</div>
											`;
			} else {filterColumns[i].innerHTML = ""};
		};

      // Filter event handler
      $(table.table().container()).on('keyup', 'thead input', function() {
         table
            .column($(this).data('index'))
            .search(this.value)
            .draw();
      });

      // Clean filters inputs by double-clicking above the head
      $(document).on("dblclick", ".ui.stackable.grid", function() {
         let inputs = document.getElementsByName("filter");
         inputs.forEach(e => {
            e.value = "";
         });
         table.search('');
         table.columns().search('').draw();
      });
      changeDatatableInputFont();
      deletePaddingTopForDatatableSegment();
		removeSortingLabel('subjects-debts');
   });
</script>

{% endblock %}